name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out my other private/public repo cape-ui
        uses: actions/checkout@master
        with:
          repository: debianmaster/nodejs-welcome
          fetch-depth: 0
      - run: |
          ls -lrt
